name: Build and test Backend

on:
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    name: Build Backend
    runs-on: slef-hosted

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        architecture: x64
    
    - name: Set up Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.8.2
        
    - name: Run the Maven verify phase
      run: mvn --batch-mode --update-snapshots verify
      working-directory: Backend
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      working-directory: Backend
